# Generated by Django 5.2.7 on 2025-10-23 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cik', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ticker', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('sic_code', models.CharField(max_length=4)),
                ('idnustrie', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('form_type', models.CharField(max_length=10)),
                ('filing_date', models.DateField()),
                ('accession_number', models.CharField(max_length=20, unique=True)),
                ('document_url', models.URLField()),
                ('raw_text', models.TextField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filings.company')),
            ],
        ),
    ]
