# Generated by Django 5.2.7 on 2025-10-23 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeDetection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section_type', models.CharField(max_length=255)),
                ('similarity_score', models.FloatField()),
                ('key_differences', models.JSONField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filings.company')),
                ('current_filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_filing', to='filings.filling')),
                ('previous_filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_filing', to='filings.filling')),
            ],
        ),
        migrations.CreateModel(
            name='FilingSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section_type', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('word_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filings.filling')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordAlert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('context_snippet', models.TextField()),
                ('detected_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filings.company')),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filings.filling')),
            ],
        ),
    ]
