# Generated by Django 5.2.7 on 2025-10-23 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0002_changedetection_filingsection_keywordalert'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filling',
            new_name='Filing',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='idnustrie',
            new_name='industry',
        ),
    ]
